### ISSUE TITLE
Callback on the main thread

### ISSUE THREAD

**Issue by jrmgx** [Augment/Augment.github.io#11]
> context: I'm going to give general feedback about the documentation,
> these are my opinions as an external developer, it is mainly based on my experience with other public SDK (ie: facebook, algolia, branch and so on)
> This is not absolute truth and I post this as issues so we can talk about it

It is more a remark about the API usage, but still,
on both platform it would be better if any callback we define runs on the main / UI thread
It should not be the developer responsability to check what thread he/she is on.
Then we could add that information in the documentation, saying: all callback will be run on the main thread

**Comment by buranmert** [comment]
We have two completion blocks in public interface:
1. `addModelToPlayer`
2. `checkIfModelDoesExistsForProduct` 

They run  in **main thread** already. However, `downloadProgress` of `addModelToPlayer` in `AugmentSDK.h` is running in background thread. Usually progress blocks run in background thread as they are called frequently.

We can say "all completion blocks run in main thread" instead of "all callbacks run in main thread". And we can change the documentation with the existing code.

**Comment by jrmgx** [comment]
Yes that would be perfect.
We should do the same on Android now.

**Comment by jrmgx** [comment]
android developers are aware of that limitation and it is worked on
